version: '2.3'
services:
  proxy:
    image: nginx:1.14.0
    volumes:
      - ${NGINX_ROOT_DIR:-.}/volumes/proxy/:/etc/nginx/conf.d/
    networks:
      - nest-network
    ports:
      - 80:80

  rate-limit-api:
    hostname: rate-limit-api
    image: valentinconan/rate-limit-api:master
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=redis
    healthcheck:
      test: wget -O /dev/null http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - nest-network

  rate-limit-api-native:
    hostname: rate-limit-api-native
    image: valentinconan/rate-limit-api-native:master
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=redis
    healthcheck:
      test: wget -O /dev/null http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "3001:3000"
    networks:
      - nest-network
  redis:
    hostname: redis
    image: 'bitnami/redis:7.2.5'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    privileged: true
    networks:
      - nest-network
networks:
  nest-network:
    driver: bridge